### ISSUE TITLE
[Question] Mod Add-on

### ISSUE THREAD

**Issue by A5ho9999** [ix0rai/rainglow#10]
I've spent the past couple days working on a small addition to the Mod at the request of some people for colouring Allays but also to make it possible to dye the squids. Just wanted to ask if you'd be willing to accept such an addon for the Mod. I was going to also look at adding _jeb however I'd like to avoid using the nametag to rather let people have actual names without changing the appearance and wasn't sure the best way to do that yet.

I can create a pull request if you are happy with it.

Changes
- Adds Coloured Allays
- Adds Dye Usage for both Squid and Allay
- Adds all Default Minecraft Colours (for Dye support)

**Comment by ix0rai** [comment]
that would be lovely, thank you!

after your pull request goes through, I'll lock each entity behind a config option (enable rainbow glow squids, enable rainglow allays, etc). I'd also like to look into implementing rainbow slimes.

one thing to consider for adding dye usage is how it'll interact on all three sides (server, client, integrated server). the mod targets all three, so just make sure to disable dye usage cleanly when the mod is only present on the client.

**Comment by A5ho9999** [comment]
Yes, I did think about the config options but figured I'd leave that as I'm not the best with the Config Screens.

I'll double check the dye on a server real quick before making the request

**Comment by ix0rai** [comment]
I'll do any additional polish I feel is necessary for release, don't worry about adding it to the configuration file yourself

**Comment by A5ho9999** [comment]
Double checked and didn't notice any issues with Mod only being client side, the dye function works but doesn't consume the dye from the player. Does consume when it's on both.

**Comment by ix0rai** [comment]
hm, I think that's fine since in the client side only case the player is the only one seeing their squids anyway. thank you again for working on this!
