### ISSUE TITLE
Allays and Slimes not gaining new colors, still vanilla.

### ISSUE THREAD

**Issue by ScrubbytheSlime** [ix0rai/rainglow#13]
Are there any dependencies I may be missing?
Glowsquids work just fine.

**Comment by ix0rai** [comment]
sorry for the incredibly late response, but I need more information than this!
please tell me:
- your version

and send:
- a log
- your config (`.minecraft/config/rainglow.toml`)

**Comment by ix0rai** [comment]
oh also the answer to your question @ScrubbytheSlime: fabric API is required on fabric, QFAPI is required on quilt. nothing else

**Comment by ix0rai** [comment]
hey, this issue has been stale for a while so I'm going to close it until I get more information. thanks!
