### ISSUE TITLE
Pride omission

### ISSUE THREAD

**Issue by allanonmage** [ix0rai/rainglow#14]
I came across your mod looking for glow ink related mobs, and will probably add it to my mod pack for me and my friends, since I think these mobs could do with some more color.  However, I'm just a boring heteronormative person, and I don't find a pride color in your list.  Can you add one?

```
pride

    transgender pride - blue, white and pink
    lesbian pride - red, orange, white, pink and purple
    bisexual pride - blue, pink and purple
    pansexual pride - pink, yellow and blue
    asexual pride - black, gray, white and purple
    aromantic pride - black, gray, white and green
    genderfluid pride - blue, pink, purple, white and black
    nonbinary pride - yellow, white, black and purple

```

**Comment by ix0rai** [comment]
I'm interpreting this as you want a generic pride mode -- i.e. the rainbow flag
this exists, but I've just labelled it "rainbow"
please tell me if this is wrong, I'm not 100% sure I understood your request!

**Comment by allanonmage** [comment]
There is no straight pride.  You have (presumably) all the other sexualities, but nothing for straight people.  I have no idea what color combination that might be though.

**Comment by mxlvilleyyy** [comment]
hello! there is no such thing as straight pride. you can be an ally, but in the end, as heterosexual, straight people are not a part of the lgbtq+ community. they have no flag, thank you

**Comment by ix0rai** [comment]
damn. I was preparing a sassy response but I will have to contain my attitude after being beaten to the punch. you have the monochrome mode at your disposal already and custom modes to create your dreams.

**Comment by allanonmage** [comment]
Why would you have a sassy attitude to a request for more colors?

**Comment by ix0rai** [comment]
a couple reasons--
- straight people have no official flag
- pride flags exist to express identities outside of cisgender and heterosexual: many lgbtq+ people consider the idea of a straight flag offensive
- you never detailed what exactly you wanted

**Comment by allanonmage** [comment]
Well, I was hoping that you knew what the straight pride flag was, since you knew all the other flags.

If gay people think the concept of a straight flag is offensive, would that not, by definition, mean that the gay flag(s) be purposefully offensive to straight people?  So what you're saying is that gay people can be rude and offensive to straight people for no reason? That doesn't make any sense.

Also, marking a feature request as "invalid" is just rude, regardless of political context.  Have you ever had a feature request marked as invalid?  That sucks balls.

**Comment by ix0rai** [comment]
So --
> If gay people think the concept of a straight flag is offensive, would that not, by definition, mean that the gay flag(s) be purposefully offensive to straight people? 

no. pride flags exist to show that you're in a community -- a community that exists independently of straight people. Since lgbtq+ people, not straight people, have begun using flags to represent themselves, lgbtq+ people feel that straight people having their own flag would be appropriation. a pride flag can't be offensive to a straight person, since the lgbtq+ people who created it are not taking anything from straight culture, so to speak.

> Also, marking a feature request as "invalid" is just rude, regardless of political context. Have you ever had a feature request marked as invalid? That sucks balls.

I did say I was going to be sassy did I not? you were warned

**Comment by ix0rai** [comment]
> Well, I was hoping that you knew what the straight pride flag was, since you knew all the other flags.

whoops missed this one
one of my lovely discord member is suggesting that it's simply alternating black and white lines -- I imagine you could make that, given that black and white are colors you have at your disposal

**Comment by Thonkman** [comment]
this... could've been handled better...
