### ISSUE TITLE
Crashes on launch with More Babies mod.

### ISSUE THREAD

**Issue by TalEdd** [ix0rai/rainglow#2]
https://mclo.gs/ac7LUtm

**Comment by ix0rai** [comment]
thank you for reporting!
I'll try to investigate this tomorrow.

**Comment by ix0rai** [comment]
this issue is caused by both mods trying to inject into the same method.
the crash is easy to fix, but it might be hard to keep rainglow's functionality intact while keeping the mods playing nice together, I'll look into it further

**Comment by ix0rai** [comment]
never mind!
I've figured out a mixin that makes rainglow work perfectly
and honestly the baby rainbow glow squids are adorable :)
release within the next few days!

**Comment by ix0rai** [comment]
released with 0.2.0
