### ISSUE TITLE
modrinth 1.2.0 marked as 1.20.1 compat but includes 1.20.2 fapi resource reloader

### ISSUE THREAD

**Issue by Linguardium** [ix0rai/rainglow#23]
title. your fabric api resource reload module include overrides the 1.20.1 fabric api resource reload module because its newer (but its for 1.20.2 so its breaks 1.20.1 installs)

**Comment by ix0rai** [comment]
metadata has been fixed for the next release and the mistake on the modrinth page has been corrected. thank you!
