### ISSUE TITLE
[bug] flickering/flashing tooltip with Inspecio mod

### ISSUE THREAD

**Issue by jadelily18** [ix0rai/rainglow#4]
With [Inspecio](https://modrinth.com/mod/inspecio) installed, hovering over a glow squid spawn egg shows a preview of the glow squid, but quickly cycling between each variant.

Tested on [Jade's Parity Plus 2.0.2](https://modrinth.com/modpack/jpp/version/v2.0.2%2B1.19.2), plus rainglow!

<details>
<summary>MASSIVE WARNING FOR EPILEPSY OR LIGHT SENSITIVITY</summary>

![image of flickering glow squid](https://i.imgur.com/Qz3sbgW.gif)

</details>

**Comment by jadelily18** [comment]
this might actually not be something you can control i think it's a bug with Inspecio sorry sorry!

**Comment by ix0rai** [comment]
yeah I noticed this during testing but I couldn't figure out a fix :(

**Comment by jadelily18** [comment]
one of the devs said it probably can't be fixed on your end when I asked about it so we'll probably just have to hope they implement a way to configure itt
