### ISSUE TITLE
Missing plugin.yml

### ISSUE THREAD

**Issue by EmanYm** [ix0rai/rainglow#6]
Missing `plugin.yml`

Mod:
- Version: 1.0.0
- MC: 1.19.3
- Released: December 11 of 2022
- Source: CurseForge

Server:
- Version: Purpur 1.19.3 build 1876
- Hosted: Locally

Error:
- Error in console during server start

> [23:15:51] [Server thread/ERROR]: Could not load 'plugins\RainGlow[v1.0.0].jar' in folder 'plugins'
> org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
> 	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:180) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:157) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
> 	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:481) ~[purpur-1.19.3.jar:git-Purpur-1876]
> 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[purpur-1.19.3.jar:git-Purpur-1876]
> 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1876]
> 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
> 	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
> Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
> 	... 7 more

Troubleshooting:
- I thought maybe it was a rare issue with a renamed jar not being recognised by itself, or maybe it was just that version, so I downloaded a version prior for MC 1.19.2.  It had the same issue.
- I downloaded the initial release from September 27 to check the archive.  It also has no plugin.yml.

**Comment by ix0rai** [comment]
Have you reported this to purpur? it's an issue on their end, since in normal usage rainglow is a fabric mod and is not expected to have a `plugin.yml`.

**Comment by EmanYm** [comment]
Every other server-side plugin I've ever installed has a plugin.yml

**Comment by EmanYm** [comment]
Why, then, is it listed when I sort by `Server`, and have `server-side optional` on the description page?

**Comment by EmanYm** [comment]
I realised after my initial post that 1.19.3 was the only version listed when I sorted the files by "server", so downloading other versions to test in my troubleshooting step was unnecessary.

**Comment by ix0rai** [comment]
Bukkit, Spigot, Paper, Purpur, etc plugins are not the only type of mod that can be used server-side. Fabric mods can also restrict themselves to client or server side.

**Comment by EmanYm** [comment]
I'm going to take your word for it, as I haven't done anything with Minecraft mod developing since pre-1.5, so you will be more knowledgeable in this area than I am.

I'll make a post to Purpur about it, but I feel like simply adding a plugin.yml would fix this issue.
Or maybe I'm completely mistaken, and it's more complicate than that.

**Comment by ix0rai** [comment]
yes, please forward this to purpur.
the reason I'm holding out on making a plugin.yml is because I have only ever worked with fabric, and aren't interested in learning about their format just to fix an issue that should be handled on purpur's side. In their software, they take rainglow and transform its code into a plugin for their own use. I'm fairly sure they maintain a rainglow codebase independent to mine, so adding one on my end wouldn't fix anything anyway.

**Comment by EmanYm** [comment]
This is true, there is options within the purpur config files.  That's how I found out about RainGlow in the first place.
Perhaps I will look a little more into the options before sending the report.

My theory is that the server-side code is there by default, and adding the mod to try and force it to work like a plugin is what **MY** issue is.  I strongly suspect this is an ID:10T error.

**Comment by ix0rai** [comment]
WAIT
yeah that's your issue
sorry I somehow managed to fixate on your issue being purpur's fault and somehow completely forgot that they implement it themselves and you're duplicating functionality anyway
if you're using purpur there's no need to install rainglow manually

**Comment by ix0rai** [comment]
don't worry about it, happy to help!
and I'm always happy to see someone who likes rainglow, it's my favourite of my projects :)
